active_stack_id: 8ae6b184-be62-4957-9903-3ed1f8876ad3
active_workspace_name: default
analytics_opt_in: true
store:
  api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzY1NjliMi1iYTNhLTQ5NmEtYTRmOS02ZGRjZTJkM2IwOTQiLCJpc3MiOiI5MDBkZWMxMi1hYzIyLTQ5YzgtOTVlYi1hMmVjOWU4NWQxYzgiLCJhdWQiOiI5MDBkZWMxMi1hYzIyLTQ5YzgtOTVlYi1hMmVjOWU4NWQxYzgifQ.UOsi17Km3CSGZ_-FvEO0H1_592USzsE0vtYxe2z-CXM
  http_timeout: 30
  password: ''
  type: rest
  url: http://127.0.0.1:8237
  username: default
  verify_ssl: true
user_id: 900dec12-ac22-49c8-95eb-a2ec9e85d1c8
version: 0.62.0
