defaults:
  - model: gradient_boosting  
  - _self_

example_version: 3
port: 5151

best_models: 
    challenger3: 'boosting_01_100_3'
    challenger2: 'boosting_01_200_3'
    challenger1: 'boosting_01_300_3'
    challenger4: 'lightgbm_01_300_5'

threshold:
  mae: 20
  r2: 0.7

split_ratio:
  train: 0.8

dataset:
  url: "parsabg/stocknewseventssentiment-snes-10"
  archive_name: 'stocknewseventssentiment-snes-10.zip'
  file_name: 'data.csv'
  name: "SNES1.0"

batch:
  size: 10000
  random_seed: 42
  counter_file: 'configs/data_version.yaml'
  save_dir: 'data/samples'

data:
  target_cols: ['Adj Close']
  cat_cols: ['GICS Sector']
  labels: 
