dataset:
  url: "parsabg/stocknewseventssentiment-snes-10"
  archive_name: 'stocknewseventssentiment-snes-10.zip'
  file_name: 'data.csv'
  name: "SNES1.0"

batch:
  size: 10000
  random_seed: 42
  counter_file: 'configs/counter.txt'
  save_dir: 'data/samples'