name: Test Model

on:
  push:
    branches:
      - main
    paths: 
      - 'src/**'
      - 'scripts/**'
      - 'services/airflow/dags/**'
      - 'tests/**'
      - 'configs/**'
      - '.github/**'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

env:
  message: "Model testing is passed!"

jobs:

  validate-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository code
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install giskard
      
      - name: Load word2vec 
        run: |
          python scripts/load_model.py

      - name: Validate model with Giskard
        run: |
          python src/validate_champion.py
          
  print_info:

      runs-on: ubuntu-latest

      # Run this job after running the job `test-code`
      needs: validate-model
      
      steps:
        - name: print message
          run: echo $message
