name: Code Testing

on:
  push:
    branches:
      - main
    paths: 
      - 'src/**'
      - 'scripts/**'
      - 'services/airflow/dags/**'
      - 'tests/**'
      - 'configs/**'
      - '.github/**'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

env:
  message: "Code testing is passed!"

# Tasks
jobs:

  test-code:

    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:

      - name: Checking out the code

        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11.0'
          cache: 'pip' 
          
      - name: install python packages
      
        run: |
            python3.11 -m pip install --upgrade pip 
            pip install -r requirements.txt 
        
      - name: Run your app
      

        run: python3.11 src/app.py &
      
      - name: Export variables
        run: | 
          echo $PWD
          export ZENML_CONFIG_PATH=$PWD/services/zenml
          export PROJECTPATH=$PWD
          export AIRFLOW_HOME=$PWD/services/airflow
          export PYTHONPATH=$PWD/src

      - name: Run ZenML server  
        run: zenml down && zenml up
        
      # Run pytest on tests folder
      - name: Test with pytest
        run: pytest tests
      

  
  print_info:

      runs-on: ubuntu-latest

      # Run this job after running the job `test-code`
      needs: test-code
      
      steps:
        - name: print message
          run: echo $message
        
